### ISSUE TITLE
MIME encode sender name

### ISSUE THREAD

**Issue by askkaz** [muratgozel/MIMEText#27] opened 2022-12-19 15:12 UTC
We have noticed some issues with sending emails with emojis in the from name. With some trial and error, we were able to send emails successfully by manually encoding this string before using `setSender`. I think the raw representation of the message should be updated in this package to automatically encode the `From` field similar to how the `Subject` field already does.

**Comment by askkaz** [comment] 2022-12-20 14:45
Here is what did not work:
```from: "✨ Hello There" <myname@example.com>```

And here is what did work:
```from: "=?utf-8?B?4pyo?= Hello There" <myname@example.com>```

I believe this is the same approach that the Subject takes.

Thanks so much for looking at this!!

**Comment by muratgozel** [comment] 2022-12-31 13:32
hey @askkaz closing this issue as its been resolved in v2.1 😌 hope it works as intended for you.

**Closed by muratgozel** 2022-12-31 13:32 UTC
